graph::addEdge
graph::addNode
graph::adj
graph::complement
graph::edgeData
graph::edgeMatrix
graph::edgemode
graph::edgeNames
graph::edges
graph::edgeWeights
graph::ftM2graphNEL
graph::graphNEL
graph::isAdjacent
graph::isConnected
graph::isDirected
graph::nodes
graph::numEdges
graph::numNodes
graph::removeEdge
graph::removeNode
graph::subGraph 
graph::ugraph 