---
title: "The bnclassify package" 
author: "Bojan Mihaljevic, Concha Bielza, Pedro Larranaga"
date: "`r Sys.Date()`"  
output:
  rmarkdown::pdf_document:
    toc: true
    number_sections: true
    keep_tex: true
    includes:
          in_header: header.tex
    citation_package: natbib 
bibliography: bnclassify.bib  
fontsize: 11pt
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- --- -->
<!-- author: -->
<!--   - name: Author One -->
<!--     affiliation: Affiliation -->
<!--     address: -->
<!--     - line 1 -->
<!--     - line 2 -->
<!--     email:  author1@work -->
<!--   - name: Author Two -->
<!--     affiliation: Affiliation -->
<!--     address: -->
<!--     - line 1 -->
<!--     - line 2 -->
<!--     email:  author2@work -->
<!-- abstract: > -->
<!--   An abstract of less than 150 words.  -->
<!-- --- -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

\input{background}

```{r child = 'usage.rmd'}
```