# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_non_reversed <- function(x) {
    .Call('_bnclassify_find_non_reversed', PACKAGE = 'bnclassify', x)
}

match_zero_based <- function(subset, superset, error_message) {
    .Call('_bnclassify_match_zero_based', PACKAGE = 'bnclassify', subset, superset, error_message)
}

ordersetdiff <- function(vector, remove) {
    .Call('_bnclassify_ordersetdiff', PACKAGE = 'bnclassify', vector, remove)
}

are_disjoint <- function(x, y) {
    .Call('_bnclassify_are_disjoint', PACKAGE = 'bnclassify', x, y)
}

normalize <- function(x) {
    .Call('_bnclassify_normalize', PACKAGE = 'bnclassify', x)
}

make_last_sideeffect <- function(x, last) {
    .Call('_bnclassify_make_last_sideeffect', PACKAGE = 'bnclassify', x, last)
}

normalize_ctgt <- function(ctgt) {
    .Call('_bnclassify_normalize_ctgt', PACKAGE = 'bnclassify', ctgt)
}

count_equal <- function(a, b) {
    .Call('_bnclassify_count_equal', PACKAGE = 'bnclassify', a, b)
}

in_rcpp <- function(element, vector) {
    .Call('_bnclassify_in_rcpp', PACKAGE = 'bnclassify', element, vector)
}

smooth_sideeffect <- function(ctgt, smooth) {
    .Call('_bnclassify_smooth_sideeffect', PACKAGE = 'bnclassify', ctgt, smooth)
}

exp_sideeffect <- function(p) {
    .Call('_bnclassify_exp_sideeffect', PACKAGE = 'bnclassify', p)
}

bh_connected_components <- function(vertices, edges) {
    .Call('_bnclassify_bh_connected_components', PACKAGE = 'bnclassify', vertices, edges)
}

bh_remove_node <- function(vertices, edges, remove) {
    .Call('_bnclassify_bh_remove_node', PACKAGE = 'bnclassify', vertices, edges, remove)
}

bh_remove_edges <- function(vertices, edges, remove_from, remove_to, edgemode) {
    .Call('_bnclassify_bh_remove_edges', PACKAGE = 'bnclassify', vertices, edges, remove_from, remove_to, edgemode)
}

bh_subgraph <- function(vertices, edges, subgraph_vertices) {
    .Call('_bnclassify_bh_subgraph', PACKAGE = 'bnclassify', vertices, edges, subgraph_vertices)
}

bh_mstree_kruskal <- function(vertices, edges, weights) {
    .Call('_bnclassify_bh_mstree_kruskal', PACKAGE = 'bnclassify', vertices, edges, weights)
}

bh_tsort <- function(vertices, edges) {
    .Call('_bnclassify_bh_tsort', PACKAGE = 'bnclassify', vertices, edges)
}

hasna_features <- function(newdata, features) {
    .Call('_bnclassify_hasna_features', PACKAGE = 'bnclassify', newdata, features)
}

hasna <- function(newdata) {
    .Call('_bnclassify_hasna', PACKAGE = 'bnclassify', newdata)
}

trim_dataset_cpp <- function(dataset, features) {
    .Call('_bnclassify_trim_dataset_cpp', PACKAGE = 'bnclassify', dataset, features)
}

graph_node_parents_inds <- function(edges, node) {
    .Call('_bnclassify_graph_node_parents_inds', PACKAGE = 'bnclassify', edges, node)
}

test_dims2columns <- function(cpt, class_var, columns_db) {
    .Call('_bnclassify_test_dims2columns', PACKAGE = 'bnclassify', cpt, class_var, columns_db)
}

get_row <- function(x, df, cptind) {
    .Call('_bnclassify_get_row', PACKAGE = 'bnclassify', x, df, cptind)
}

fill_vector <- function(size, row, rcpt, df, features, class_var) {
    .Call('_bnclassify_fill_vector', PACKAGE = 'bnclassify', size, row, rcpt, df, features, class_var)
}

make_cpt_object <- function(x, class_var) {
    invisible(.Call('_bnclassify_make_cpt_object', PACKAGE = 'bnclassify', x, class_var))
}

call_model_fun <- function(x, funct) {
    .Call('_bnclassify_call_model_fun', PACKAGE = 'bnclassify', x, funct)
}

compute_joint <- function(x, newdata) {
    .Call('_bnclassify_compute_joint', PACKAGE = 'bnclassify', x, newdata)
}

entry_index <- function(indices, dim_prod) {
    .Call('_bnclassify_entry_index', PACKAGE = 'bnclassify', indices, dim_prod)
}

tabulate_cpp <- function(v, nlevels) {
    .Call('_bnclassify_tabulate_cpp', PACKAGE = 'bnclassify', v, nlevels)
}

table_cpp <- function(input, columns) {
    .Call('_bnclassify_table_cpp', PACKAGE = 'bnclassify', input, columns)
}

