# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entry_index <- function(indices, dim_prod) {
    .Call('_bnclassify_entry_index', PACKAGE = 'bnclassify', indices, dim_prod)
}

match_zero_based <- function(features, columns_db) {
    .Call('_bnclassify_match_zero_based', PACKAGE = 'bnclassify', features, columns_db)
}

ordersetdiff <- function(vector, remove) {
    .Call('_bnclassify_ordersetdiff', PACKAGE = 'bnclassify', vector, remove)
}

hasna <- function(newdata) {
    .Call('_bnclassify_hasna', PACKAGE = 'bnclassify', newdata)
}

are_disjoint <- function(x, y) {
    .Call('_bnclassify_are_disjoint', PACKAGE = 'bnclassify', x, y)
}

normalize <- function(x) {
    .Call('_bnclassify_normalize', PACKAGE = 'bnclassify', x)
}

normalize_ctgt <- function(ctgt) {
    .Call('_bnclassify_normalize_ctgt', PACKAGE = 'bnclassify', ctgt)
}

call_model_fun <- function(x, funct) {
    .Call('_bnclassify_call_model_fun', PACKAGE = 'bnclassify', x, funct)
}

compute_joint <- function(x, newdata) {
    .Call('_bnclassify_compute_joint', PACKAGE = 'bnclassify', x, newdata)
}

test_dims2columns <- function(cpt, class_var, columns_db) {
    .Call('_bnclassify_test_dims2columns', PACKAGE = 'bnclassify', cpt, class_var, columns_db)
}

get_row <- function(x, df, cptind) {
    .Call('_bnclassify_get_row', PACKAGE = 'bnclassify', x, df, cptind)
}

fill_vector <- function(size, row, rcpt, df, features, class_var) {
    .Call('_bnclassify_fill_vector', PACKAGE = 'bnclassify', size, row, rcpt, df, features, class_var)
}

make_cpt_object <- function(x, class_var) {
    invisible(.Call('_bnclassify_make_cpt_object', PACKAGE = 'bnclassify', x, class_var))
}

table_cpp <- function(v) {
    .Call('_bnclassify_table_cpp', PACKAGE = 'bnclassify', v)
}

unidim_values <- function(data) {
    .Call('_bnclassify_unidim_values', PACKAGE = 'bnclassify', data)
}

