# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

are_disjoint <- function(x, y) {
    .Call('_bnclassify_are_disjoint', PACKAGE = 'bnclassify', x, y)
}

normalize <- function(x) {
    .Call('_bnclassify_normalize', PACKAGE = 'bnclassify', x)
}

normalize_ctgt <- function(ctgt) {
    .Call('_bnclassify_normalize_ctgt', PACKAGE = 'bnclassify', ctgt)
}

hasna <- function(newdata) {
    .Call('_bnclassify_hasna', PACKAGE = 'bnclassify', newdata)
}

dostop <- function() {
    invisible(.Call('_bnclassify_dostop', PACKAGE = 'bnclassify'))
}

compute_joint <- function(x, newdata) {
    .Call('_bnclassify_compute_joint', PACKAGE = 'bnclassify', x, newdata)
}

table_cpp <- function(v) {
    .Call('_bnclassify_table_cpp', PACKAGE = 'bnclassify', v)
}

unidim_values <- function(data) {
    .Call('_bnclassify_unidim_values', PACKAGE = 'bnclassify', data)
}

